### ISSUE TITLE
No module named 'lib.common'

### ISSUE THREAD

**Issue by LaIMirch** [xz-zone/Webpackfind#5]
使用了阿里和清华的源都找不到这个库

**Comment by 1lkla** [comment]
腾讯和豆瓣也不行

**Comment by xz-zone** [comment]
> 腾讯和豆瓣也不行

这个是本地的 截图下lib这个目录

**Comment by xz-zone** [comment]
> 使用了阿里和清华的源都找不到这个库

这个是本地的 截图下lib这个目录

**Comment by LaIMirch** [comment]
![图片](https://user-images.githubusercontent.com/44455803/191408018-242c50d3-d5ac-43a0-bc3c-669ddcb10a9d.png)

**Comment by xz-zone** [comment]
> ![图片](https://user-images.githubusercontent.com/44455803/191408018-242c50d3-d5ac-43a0-bc3c-669ddcb10a9d.png)

Webpackfind/lib/common 这个目录

**Comment by LaIMirch** [comment]
> > ![图片](https://user-images.githubusercontent.com/44455803/191408018-242c50d3-d5ac-43a0-bc3c-669ddcb10a9d.png)
> 
> Webpackfind/lib/common 这个目录

![图片](https://user-images.githubusercontent.com/44455803/191409423-e633e308-e829-42c7-accf-749aee517eaa.png)

**Comment by xz-zone** [comment]
> > > ![图片](https://user-images.githubusercontent.com/44455803/191408018-242c50d3-d5ac-43a0-bc3c-669ddcb10a9d.png)
> > 
> > 
> > Webpackfind/lib/common 这个目录
> 
> ![图片](https://user-images.githubusercontent.com/44455803/191409423-e633e308-e829-42c7-accf-749aee517eaa.png)

好的 我本地测试下  我看看有没有问题

**Comment by xz-zone** [comment]
> > > ![图片](https://user-images.githubusercontent.com/44455803/191408018-242c50d3-d5ac-43a0-bc3c-669ddcb10a9d.png)
> > 
> > 
> > Webpackfind/lib/common 这个目录
> 
> ![图片](https://user-images.githubusercontent.com/44455803/191409423-e633e308-e829-42c7-accf-749aee517eaa.png)

![image](https://user-images.githubusercontent.com/19305748/191423199-cc747478-a170-42b3-8137-426c6b644af1.png)
没问题，你重新拉去下试下

**Comment by LaIMirch** [comment]
> 

执行main.py可以，进到lib目录下执行webpackfind.py就会报错

**Comment by xz-zone** [comment]
> > 
> 
> 执行main.py可以，进到lib目录下执行webpackfind.py就会报错

不应该把，一般调用main.py的
